# Generated by Django 5.2.7 on 2025-10-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="heatmappoint",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="heatmappoint",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("flood", "Flood"),
                    ("earthquake", "Earthquake"),
                    ("fire", "Fire"),
                    ("roadblock", "Roadblock"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
