# Generated by Django 5.2.7 on 2025-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_heatmappoint_intensity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heatmappoint",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
