# Generated by Django 5.2.7 on 2025-10-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_heatmappoint_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="heatmappoint",
            name="duration",
            field=models.IntegerField(default=60),
        ),
    ]
