# Generated by Django 4.2.25 on 2025-10-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_sosalert"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("dispatched", "Dispatched"),
                            ("en_route", "En Route"),
                            ("on_scene", "On Scene"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("team_leader", "Team Leader"),
                            ("coordinator", "Coordinator"),
                            ("field_responder", "Field Responder"),
                            ("medical_staff", "Medical Staff"),
                            ("logistics", "Logistics"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("fire", "Fire Department"),
                            ("medical", "Medical Emergency"),
                            ("police", "Police"),
                            ("rescue", "Rescue Team"),
                            ("relief", "Relief Distribution"),
                        ],
                        max_length=20,
                    ),
                ),
                ("badge_number", models.CharField(max_length=50, unique=True)),
                ("certification", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_duty", "On Duty"),
                            ("off_duty", "Off Duty"),
                            ("busy", "Busy"),
                            ("available", "Available"),
                        ],
                        default="off_duty",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api.incidentassignment",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.teammember"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incidentassignment",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_incidents",
                to="api.teammember",
            ),
        ),
        migrations.AddField(
            model_name="incidentassignment",
            name="sos_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="api.sosreport",
            ),
        ),
    ]
