# Generated by Django 4.2.25 on 2025-10-30 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0012_incidentstatistics_resource_resourcetype_teammessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("fire", "Fire Department"),
                            ("medical", "Medical Emergency"),
                            ("police", "Police"),
                            ("rescue", "Rescue Team"),
                            ("relief", "Relief Distribution"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("max_members", models.IntegerField(default=50)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_teams",
                        to="api.teammember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "role_in_team",
                    models.CharField(
                        choices=[
                            ("team_leader", "Team Leader"),
                            ("coordinator", "Coordinator"),
                            ("field_responder", "Field Responder"),
                            ("medical_staff", "Medical Staff"),
                            ("logistics", "Logistics"),
                        ],
                        default="field_responder",
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="api.teammember",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "member")},
            },
        ),
        migrations.CreateModel(
            name="TeamJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("team_leader", "Team Leader"),
                            ("coordinator", "Coordinator"),
                            ("field_responder", "Field Responder"),
                            ("medical_staff", "Medical Staff"),
                            ("logistics", "Logistics"),
                        ],
                        default="field_responder",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="api.teammember",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "unique_together": {("team", "member")},
            },
        ),
    ]
