# Generated by Django 4.2.25 on 2025-10-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_team_teammembership_teamjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="sosreport",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sosreport",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="sosreport",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
